name: Build Informant Extension

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false

      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Package extension
        run: vsce package

      - name: Show package
        run: ls -lh *.vsix

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v6
        with:
          name: informant-vsix
          path: "*.vsix"
